# wispbox build pipeline.
# Node.js is required at BUILD time only; the release binaries embed the
# compiled frontend and run with zero runtime dependencies beyond
# Postfix/Dovecot/systemd.

VERSION ?= 0.1.0-dev
COMMIT  ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
DATE    ?= $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
LDFLAGS  = -s -w \
  -X github.com/xiqi/wispbox/internal/buildinfo.Version=$(VERSION) \
  -X github.com/xiqi/wispbox/internal/buildinfo.Commit=$(COMMIT) \
  -X github.com/xiqi/wispbox/internal/buildinfo.Date=$(DATE)

.PHONY: all frontend backend build test lint dev clean release

all: build

frontend:
	cd web && npm install --no-audit --no-fund && npm run build

backend: frontend
	go build -ldflags '$(LDFLAGS)' -o wispboxd ./cmd/wispboxd
	go build -ldflags '$(LDFLAGS)' -o wispboxctl ./cmd/wispboxctl

build: frontend backend

test: frontend
	go test ./...

lint: frontend
	go vet ./...
	cd web && npx tsc --noEmit

# Run the daemon in development mode: mock adapters, high ports, ./devdata.
dev: frontend
	go run ./cmd/wispboxd serve --dev

clean:
	rm -f wispboxd wispboxctl
	rm -rf web/dist devdata dist

# Cross-compile release binaries (CGO-free thanks to modernc.org/sqlite).
# dist/ ends up containing everything install.sh downloads for a release:
# both binaries for amd64+arm64 plus the systemd unit. Checksums (SHA256SUMS)
# are generated by the release workflow so there is one canonical generator.
release: frontend
	mkdir -p dist
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '$(LDFLAGS)' -o dist/wispboxd_linux_amd64 ./cmd/wispboxd
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags '$(LDFLAGS)' -o dist/wispboxd_linux_arm64 ./cmd/wispboxd
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '$(LDFLAGS)' -o dist/wispboxctl_linux_amd64 ./cmd/wispboxctl
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags '$(LDFLAGS)' -o dist/wispboxctl_linux_arm64 ./cmd/wispboxctl
	cp packaging/systemd/wispboxd.service dist/wispboxd.service
	cp packaging/systemd/wispbox-upgrade.service dist/wispbox-upgrade.service
	cp packaging/upgrade.sh dist/wispbox-upgrade.sh
