package configgen

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/xiqi/wispbox/internal/db"
	"github.com/xiqi/wispbox/internal/services"
)

// Generator renders and applies the full configuration set.
//
// Fail-safe contract:
//  1. Build data from the DB; abort on inconsistency.
//  2. Render every file in memory; abort on any template error.
//  3. Only then write files, each atomically (temp file + rename).
//  4. Only after all writes succeed, reload services.
//
// A failure in steps 1–2 leaves the previous generated config untouched, so
// Postfix/Dovecot keep running on the last good configuration.
type Generator struct {
	Builder        *Builder
	Services       services.Manager
	Store          *db.Store
	Log            *slog.Logger
	ReloadServices bool // false for `config render` CLI runs
}

// Apply regenerates everything under GeneratedDir and reloads services.
func (g *Generator) Apply(ctx context.Context) error {
	data, files, err := g.RenderAll(ctx)
	if err != nil {
		_ = g.Store.AppendServiceEvent(ctx, db.ServiceEvent{
			Service: "wispboxd", EventType: "config_apply", Status: "error", Message: err.Error(),
		})
		return err
	}

	for path, content := range files {
		if err := writeAtomic(path, content); err != nil {
			_ = g.Store.AppendServiceEvent(ctx, db.ServiceEvent{
				Service: "wispboxd", EventType: "config_apply", Status: "error",
				Message: fmt.Sprintf("write %s: %v", path, err),
			})
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	if g.ReloadServices {
		targets := []string{"postfix", "dovecot"}
		if data.DKIMEnabled {
			targets = append(targets, "opendkim")
		}
		var reloadErrs []string
		for _, svc := range targets {
			if err := g.Services.Reload(ctx, svc); err != nil {
				g.logger().Warn("service reload failed", "service", svc, "error", err)
				reloadErrs = append(reloadErrs, err.Error())
			}
		}
		if len(reloadErrs) > 0 {
			msg := strings.Join(reloadErrs, "; ")
			_ = g.Store.AppendServiceEvent(ctx, db.ServiceEvent{
				Service: "wispboxd", EventType: "config_apply", Status: "error",
				Message: msg,
			})
			return fmt.Errorf("reload generated configuration: %s", msg)
		}
	}
	_ = g.Store.AppendServiceEvent(ctx, db.ServiceEvent{
		Service: "wispboxd", EventType: "config_apply", Status: "ok",
		Message: fmt.Sprintf("%d files generated", len(files)),
	})
	return nil
}

// RenderAll renders every generated file fully in memory. It returns the
// assembled Data (so callers can reuse it without a second DB pass) and a map
// of absolute path -> content. Nothing is written.
func (g *Generator) RenderAll(ctx context.Context) (*Data, map[string][]byte, error) {
	data, err := g.Builder.Build(ctx)
	if err != nil {
		return nil, nil, fmt.Errorf("assemble configuration data: %w", err)
	}
	if err := data.Validate(); err != nil {
		return nil, nil, fmt.Errorf("refusing to generate config: %w", err)
	}

	files := map[string][]byte{}

	pf, err := RenderPostfix(data)
	if err != nil {
		return nil, nil, fmt.Errorf("render postfix config: %w", err)
	}
	for name, content := range pf {
		files[filepath.Join(data.PostfixMapDir, name)] = content
	}

	dc, err := RenderDovecot(data)
	if err != nil {
		return nil, nil, fmt.Errorf("render dovecot config: %w", err)
	}
	for name, content := range dc {
		files[filepath.Join(data.GeneratedDovecotDir, name)] = content
	}

	dk, err := renderOpenDKIM(data)
	if err != nil {
		return nil, nil, fmt.Errorf("render opendkim config: %w", err)
	}
	for name, content := range dk {
		files[filepath.Join(data.GeneratedOpenDKIMDir, name)] = content
	}
	return data, files, nil
}

func renderOpenDKIM(d *Data) (map[string][]byte, error) {
	conf, err := renderTemplate("opendkim/templates/opendkim.conf.tmpl", d)
	if err != nil {
		return nil, err
	}
	out := map[string][]byte{"opendkim.conf": conf}

	var keyTable, signingTable bytes.Buffer
	keyTable.WriteString("# Generated by wispbox. DO NOT EDIT.\n")
	signingTable.WriteString("# Generated by wispbox. DO NOT EDIT.\n")
	for _, k := range d.DKIMKeys {
		fmt.Fprintf(&keyTable, "%s._domainkey.%s %s:%s:%s\n", k.Selector, k.Domain, k.Domain, k.Selector, k.KeyPath)
		fmt.Fprintf(&signingTable, "*@%s %s._domainkey.%s\n", k.Domain, k.Selector, k.Domain)
	}
	out["key.table"] = keyTable.Bytes()
	out["signing.table"] = signingTable.Bytes()
	return out, nil
}

func (g *Generator) logger() *slog.Logger {
	if g.Log != nil {
		return g.Log
	}
	return slog.Default()
}

// writeAtomic writes content via a temp file + rename in the target dir.
// sasl_passwd carries relay credentials, so map files are 0640.
func writeAtomic(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".tmp-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return err
	}
	mode := os.FileMode(0o640)
	if filepath.Base(path) == "sasl_passwd" {
		mode = 0o600
	}
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
