package configgen

import (
	"fmt"
	"sort"
	"strings"
)

// RenderPostfix produces every Postfix file as name -> content. Rendering is
// pure: no filesystem access, no host effects. Callers decide where (and
// whether) to write them.
func RenderPostfix(d *Data) (map[string][]byte, error) {
	out := map[string][]byte{}

	for _, t := range []struct{ name, tmpl string }{
		{"main.cf", "postfix/templates/main.cf.tmpl"},
		{"master.cf", "postfix/templates/master.cf.tmpl"},
	} {
		body, err := renderTemplate(t.tmpl, d)
		if err != nil {
			return nil, err
		}
		out[t.name] = body
	}

	out["virtual_domains"] = renderMap(virtualDomainLines(d))
	out["virtual_mailboxes"] = renderMap(virtualMailboxLines(d))
	out["virtual_aliases"] = renderMap(virtualAliasLines(d))
	out["sender_logins"] = renderMap(senderLoginLines(d))
	out["sender_transport"] = renderMap(senderTransportLines(d))
	out["sasl_passwd"] = renderMap(saslLines(d))
	out["tls_policy"] = renderMap(tlsPolicyLines(d))
	out["sni_maps"] = renderMap(sniLines(d))
	return out, nil
}

// renderMap formats key/value pairs as a Postfix texthash file.
func renderMap(lines [][2]string) []byte {
	var b strings.Builder
	b.WriteString("# Generated by wispbox. DO NOT EDIT.\n")
	sort.SliceStable(lines, func(i, j int) bool { return lines[i][0] < lines[j][0] })
	for _, kv := range lines {
		if kv[0] == "" {
			continue
		}
		fmt.Fprintf(&b, "%s %s\n", kv[0], kv[1])
	}
	return []byte(b.String())
}

func virtualDomainLines(d *Data) [][2]string {
	var lines [][2]string
	for _, dom := range d.Domains {
		lines = append(lines, [2]string{dom.Name, "OK"})
	}
	return lines
}

func virtualMailboxLines(d *Data) [][2]string {
	var lines [][2]string
	for _, m := range d.Mailboxes {
		if !m.Enabled {
			continue
		}
		local, domain, ok := strings.Cut(m.Email, "@")
		if !ok {
			continue
		}
		lines = append(lines, [2]string{m.Email, domain + "/" + local + "/Maildir/"})
	}
	return lines
}

func virtualAliasLines(d *Data) [][2]string {
	var lines [][2]string
	for _, a := range d.Aliases {
		if !a.Enabled {
			continue
		}
		lines = append(lines, [2]string{a.Source, a.Destination})
	}
	return lines
}

func senderLoginLines(d *Data) [][2]string {
	var lines [][2]string
	for _, sl := range d.SenderLogins {
		lines = append(lines, [2]string{sl.Sender, strings.Join(sl.Owners, ",")})
	}
	return lines
}

func senderTransportLines(d *Data) [][2]string {
	var lines [][2]string
	for _, st := range d.SenderTransports {
		lines = append(lines, [2]string{st.SenderKey, st.Transport})
	}
	return lines
}

func saslLines(d *Data) [][2]string {
	var lines [][2]string
	for _, e := range d.SASLEntries {
		lines = append(lines, [2]string{e.Nexthop, e.Credentials})
	}
	return lines
}

func tlsPolicyLines(d *Data) [][2]string {
	var lines [][2]string
	for _, p := range d.TLSPolicies {
		lines = append(lines, [2]string{p.Nexthop, p.Policy})
	}
	return lines
}

func sniLines(d *Data) [][2]string {
	var lines [][2]string
	for _, s := range d.SNI {
		lines = append(lines, [2]string{s.Hostname, s.KeyPath + " " + s.CertPath})
	}
	return lines
}
